### PR TITLE
fix zone creation with nsec3param - https://github.com/joeig/go-powerdns/issues/27

### PR DESCRIPTION
**Pull request by apolubotko**
* [x] Does your submission pass all tests against mocks? `make test`
* [ ] Does your submission pass all tests against a real instance running PowerDNS Authoritative Server 4.1, 4.2 and 4.3? `docker-compose -f docker-compose-v4.3.yml up && make test-without-mocks`
* [ ] Do your tests meet or exceed the coverage results of the master branch? `make coverage && go tool cover -html=c.out`
* [ ] Does your submission pass the format guidelines? `make check-fmt`

Furthermore, the pipeline performs additional checks against your submission:

* [ ] Does your submission comply with common best practices? `golangci-lint run && staticcheck ./...`

### CODE REVIEW

**Comment by joeig** [comment]
Thanks for PR #28. This is reproducible with the `AddNative` and `AddMaster` methods. Alternatively you could use the a bit more low-level `Add` method, which allows you to specify the entire `Zone` by yourself.

Can I ask you to add a unit test for your change, so that I won't get missed if we ever refactor the codebase? If this is in place, I'm happy to merge.

**Comment by apolubotko** [comment]
Hello!

Thanks for prompting `Add` method it actually helped me, also I added a couple of tests in the last commit.

**Comment by apolubotko** [comment]
Hello, @joeig 

Please check the tests

**Review by joeig — APPROVED** [review]

**Comment by joeig** [comment]
Thank you!

**Pull request merged**
